### PR TITLE
fix: About Page fr translations

### PR DESCRIPTION
**Pull request by corrinachow**
## ✅ Changes

- fix: About page French translation

## 🔒Checklist

- I tested my work on the feature environment

## 💅 Examples

image

### CODE REVIEW

**Comment by RPDeshaies** [comment]
Fixed v3.2.0 build, you can rebase and your build should be fixed

**Comment by corrinachow** [comment]
@RPDeshaies Looks like the tests pass but the build is still failing on the preview deployment step for [feat/3.2.0](https://github.com/fariapp/fari/pull/113) but I've rebased and pushed the changes.

**Comment by RPDeshaies** [comment]
Netlify went down yesterday (timeout error) I'll try to redeploy today and see if its good now

**Comment by RPDeshaies** [comment]
The netlify CLI was broken, I udpated it to the latest version (see [commit](https://github.com/fariapp/fari/pull/113/commits/31324ec0d7ee7abc5f524e64f99b5e2aa73c86c1))

If you rebase again it _should_ be fine.

Here's a working build on v3.2.0

https://dev.azure.com/fariapp/fari/_build/results?buildId=198&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1601c4c-45d5-58f9-2d01-127ffe91cde0

**Comment by corrinachow** [comment]
Rebased to [31324ec](https://github.com/fariapp/fari/pull/113/commits/31324ec0d7ee7abc5f524e64f99b5e2aa73c86c1) and no dice 😢

**Comment by RPDeshaies** [comment]
I don't have the time to fix the build but your changes look good to me. I'll merge. Thanks for this @corrinachow

**Pull request merged**
