### PR TITLE
feat: v3.4.0 (new join screen, italian translations)

### PR DESCRIPTION
**Pull request by RPDeshaies**
## ✅ Changes

- feat: new join screen
- feat: load character sheet in player row
- feat: change character sheet in player row
- feat: italian translations 👏 #191 @Redjaw

## 💅 Examples

image
image
image
image

### CODE REVIEW

**Comment by RPDeshaies** [comment]
@Redjaw I had to add 3 new translation keys that I translated with Google Translate but if you have better suggestions, I'm all ears

```
  "play-route.add-character-sheet": `Aggiungi la scheda del personaggio`,
  "play-route.what-is-your-name": `Come ti chiami`,
  "player-row.swap-character-sheet": `Scambia la scheda del personaggio`,
```

**Comment by Redjaw** [comment]
> @Redjaw I had to add 3 new translation keys that I translated with Google Translate but if you have better suggestions, I'm all ears
> 
> ```
>   "play-route.add-character-sheet": `Aggiungi la scheda del personaggio`,
>   "play-route.what-is-your-name": `Come ti chiami`,
>   "player-row.swap-character-sheet": `Scambia la scheda del personaggio`,
> ```

Those are quite good, I had to update to get them. Let me know of you need more in the future!

**Comment by RPDeshaies** [comment]
Will do ! Thanks again!

**Comment by RPDeshaies** [comment]
@all-contributors add @Redjaw to i18n

**Comment by RPDeshaies** [comment]
@all-contributors add @Redjaw to translation

**Pull request merged**
